# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.IntegerField(primary_key=True, serialize=False)),
                ('companyName', models.IntegerField(max_length=45, primary_key=True)),
                ('companyLogoUrl', models.URLField(max_length=100)),
                ('companyAddress', models.CharField(max_length=100)),
                ('companySite', models.URLField(max_length=100)),
                ('companyCreatAt', models.DateTimeField(default='CURRENT_TIMESTAMP ')),
                ('companyFlag', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depID', models.IntegerField(primary_key=True, serialize=False)),
                ('depName', models.IntegerField(max_length=45, primary_key=True)),
                ('depcompanyID', models.IntegerField(max_length=8, primary_key=True)),
                ('depParentID', models.IntegerField(max_length=45, primary_key=True)),
                ('depLogoUrl', models.URLField(max_length=100)),
                ('depAddress', models.CharField(max_length=100)),
                ('depSite', models.URLField(max_length=100)),
                ('depCreatAt', models.DateTimeField(default='CURRENT_TIMESTAMP ')),
                ('depFlag', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('rightCode', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('rightText', models.CharField(max_length=100)),
                ('rightParentCode', models.IntegerField(max_length=8)),
                ('rightType', models.IntegerField(max_length=45)),
                ('rightUrl', models.URLField(max_length=100)),
                ('rightTip', models.IntegerField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=45, unique=True)),
                ('roleFlag', models.IntegerField(default='1', max_length=2)),
                ('roleCreateAt', models.DateTimeField(default='CURRENT_TIMESTAMP ')),
            ],
        ),
        migrations.CreateModel(
            name='RoleRight',
            fields=[
                ('rfRoleId', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('rfRightCode', models.IntegerField(max_length=8, primary_key=True)),
                ('rfFlag', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('roleToUserID', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('userToRoleID', models.IntegerField(max_length=8, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('test', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=45, unique=True)),
                ('userPassword', models.CharField(max_length=30)),
                ('userMobile', models.IntegerField(max_length=11, unique=True)),
                ('userEmail', models.IntegerField(max_length=45, unique=True)),
                ('userType', models.IntegerField(default='0', max_length=2)),
                ('userFlag', models.IntegerField(default='1', max_length=2)),
                ('userCreateAt', models.DateTimeField(default='CURRENT_TIMESTAMP ')),
            ],
        ),
    ]
