# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyFlag',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='department',
            name='depFlag',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleFlag',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='roleright',
            name='rfFlag',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFlag',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.IntegerField(default='0'),
        ),
    ]
