# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170827_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='depName',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='depParentID',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='depcompanyID',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='right',
            name='rightTip',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='right',
            name='rightType',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='roleright',
            name='rfRightCode',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='roleright',
            name='rfRoleId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='roleToUserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='userToRoleID',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userMobile',
            field=models.IntegerField(unique=True),
        ),
    ]
