# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('rightCode', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('rightText', models.CharField(max_length=100)),
                ('rightParentCode', models.IntegerField(max_length=8)),
                ('rightType', models.IntegerField(max_length=45)),
                ('rightUrl', models.IntegerField(max_length=100)),
                ('rightTip', models.IntegerField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=45, unique=True)),
                ('roleFlag', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRight',
            fields=[
                ('rfRoleid', models.IntegerField(primary_key=True, serialize=False)),
                ('rfRightCode', models.IntegerField(primary_key=True)),
                ('roleFlag', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='test',
        ),
    ]
