# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170826_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleright',
            old_name='roleFlag',
            new_name='rfFlag',
        ),
        migrations.AlterField(
            model_name='roleright',
            name='rfRightCode',
            field=models.IntegerField(max_length=8, primary_key=True),
        ),
        migrations.AlterField(
            model_name='roleright',
            name='rfRoleid',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
