# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170826_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('depID', models.IntegerField(primary_key=True, serialize=False)),
                ('depName', models.IntegerField(max_length=45, primary_key=True)),
                ('depcompanyID', models.IntegerField(max_length=8, primary_key=True)),
                ('depParentID', models.IntegerField(max_length=45, primary_key=True)),
                ('depLogoUrl', models.URLField(max_length=100)),
                ('depAddress', models.CharField(max_length=100)),
                ('depSite', models.URLField(max_length=100)),
                ('depCreatAt', models.DateTimeField(default='CURRENT_TIMESTAMP ')),
                ('depFlag', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleRight',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
