# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170827_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='depFlag',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='depName',
            field=models.CharField(max_length=45, primary_key=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='depParentID',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='depcompanyID',
            field=models.IntegerField(primary_key=True),
        ),
    ]
